export const userTypes = {
  LOGIN_USER: 'LOGIN_USER',
  USER_LOGIN_SUCCEED: 'USER_LOGIN_SUCCEED',
  POST_CERTAIN_USER: 'POST_CERTAIN_USER',
  POST_CERTAIN_USER_SUCCEED: 'POST_CERTAIN_USER_SUCCEED',
  SET_AUTHENTICATION_STATE: 'SET_AUTHENTICATION_STATE',
  USER_SIGN_OUT: 'USER_SIGN_OUT'
};

export const textTypes = {};

export const loadingType = {
  CHANGE_LOADING_STATE: 'CHANGE_LOADING_STATE',
};

export const errorType = {
  SET_ERROR_STATE: 'SET_ERROR_STATE',
  SET_ALERT: 'SET_ALERT',
  REMOVE_ALERT: 'REMOVE_ALERT',
};
