export const userTypes = {
  LOGIN_USER: 'LOGIN_USER',
  USER_LOGIN_SUCCEED: 'USER_LOGIN_SUCCEED',
  POST_CERTAIN_USER: 'POST_CERTAIN_USER',
  POST_CERTAIN_USER_SUCCEED: 'POST_CERTAIN_USER_SUCCEED',
  SET_AUTHENTICATION_STATE: 'SET_AUTHENTICATION_STATE',
  USER_SIGN_OUT: 'USER_SIGN_OUT',
  SET_USER_ERROR_STATE: 'SET_USER_ERROR_STATE',
};

export const textTypes = {
  GET_RANDOM_TEXT: 'GET_RANDOM_TEXT',
  GET_RANDOM_TEXT_SUCCEED: 'GET_RANDOM_TEXT_SUCCEED',
  CLEAR_RANDOM_TEXT: 'CLEAR_RANDOM_TEXT',
  GET_LAST_WPM_RESULT: 'GET_LAST_WPM_RESULT',
  GET_LAST_WPM_RESULT_SUCCEED: 'GET_LAST_WPM_RESULT_SUCCEED',
  PUT_LAST_WPM_RESULT: 'PUT_LAST_WPM_RESULT',
  SET_TEXT_ERROR_STATE: 'SET_TEXT_ERROR_STATE'
};

export const loadingType = {
  CHANGE_LOADING_STATE: 'CHANGE_LOADING_STATE',
};

export const alertType = {
  SET_ALERT: 'SET_ALERT',
  REMOVE_ALERT: 'REMOVE_ALERT',
};
